// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIV1BBucketNameEntryNameReader is a Reader for the GetAPIV1BBucketNameEntryName structure.
type GetAPIV1BBucketNameEntryNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1BBucketNameEntryNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1BBucketNameEntryNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetAPIV1BBucketNameEntryNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1BBucketNameEntryNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1BBucketNameEntryNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1BBucketNameEntryNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV1BBucketNameEntryNameUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/b/{bucket_name}/{entry_name}] GetAPIV1BBucketNameEntryName", response, response.Code())
	}
}

// NewGetAPIV1BBucketNameEntryNameOK creates a GetAPIV1BBucketNameEntryNameOK with default headers values
func NewGetAPIV1BBucketNameEntryNameOK() *GetAPIV1BBucketNameEntryNameOK {
	return &GetAPIV1BBucketNameEntryNameOK{}
}

/*
GetAPIV1BBucketNameEntryNameOK describes a response with status code 200, with default header values.

The record is found and returned in body of the response
*/
type GetAPIV1BBucketNameEntryNameOK struct {
	Payload string
}

// IsSuccess returns true when this get Api v1 b bucket name entry name o k response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 b bucket name entry name o k response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name o k response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 b bucket name entry name o k response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name o k response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 b bucket name entry name o k response
func (o *GetAPIV1BBucketNameEntryNameOK) Code() int {
	return 200
}

func (o *GetAPIV1BBucketNameEntryNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameOK %s", 200, payload)
}

func (o *GetAPIV1BBucketNameEntryNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameOK %s", 200, payload)
}

func (o *GetAPIV1BBucketNameEntryNameOK) GetPayload() string {
	return o.Payload
}

func (o *GetAPIV1BBucketNameEntryNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1BBucketNameEntryNameNoContent creates a GetAPIV1BBucketNameEntryNameNoContent with default headers values
func NewGetAPIV1BBucketNameEntryNameNoContent() *GetAPIV1BBucketNameEntryNameNoContent {
	return &GetAPIV1BBucketNameEntryNameNoContent{}
}

/*
GetAPIV1BBucketNameEntryNameNoContent describes a response with status code 204, with default header values.

No Content - If there is no record available for the given query
*/
type GetAPIV1BBucketNameEntryNameNoContent struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name no content response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 b bucket name entry name no content response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name no content response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 b bucket name entry name no content response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name no content response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get Api v1 b bucket name entry name no content response
func (o *GetAPIV1BBucketNameEntryNameNoContent) Code() int {
	return 204
}

func (o *GetAPIV1BBucketNameEntryNameNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameNoContent", 204)
}

func (o *GetAPIV1BBucketNameEntryNameNoContent) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameNoContent", 204)
}

func (o *GetAPIV1BBucketNameEntryNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameUnauthorized creates a GetAPIV1BBucketNameEntryNameUnauthorized with default headers values
func NewGetAPIV1BBucketNameEntryNameUnauthorized() *GetAPIV1BBucketNameEntryNameUnauthorized {
	return &GetAPIV1BBucketNameEntryNameUnauthorized{}
}

/*
GetAPIV1BBucketNameEntryNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized - Access token is invalid or empty
*/
type GetAPIV1BBucketNameEntryNameUnauthorized struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name unauthorized response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name unauthorized response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name unauthorized response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name unauthorized response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name unauthorized response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 b bucket name entry name unauthorized response
func (o *GetAPIV1BBucketNameEntryNameUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1BBucketNameEntryNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameUnauthorized", 401)
}

func (o *GetAPIV1BBucketNameEntryNameUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameUnauthorized", 401)
}

func (o *GetAPIV1BBucketNameEntryNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameForbidden creates a GetAPIV1BBucketNameEntryNameForbidden with default headers values
func NewGetAPIV1BBucketNameEntryNameForbidden() *GetAPIV1BBucketNameEntryNameForbidden {
	return &GetAPIV1BBucketNameEntryNameForbidden{}
}

/*
GetAPIV1BBucketNameEntryNameForbidden describes a response with status code 403, with default header values.

Forbidden - Access token denied
*/
type GetAPIV1BBucketNameEntryNameForbidden struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name forbidden response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name forbidden response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name forbidden response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name forbidden response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name forbidden response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 b bucket name entry name forbidden response
func (o *GetAPIV1BBucketNameEntryNameForbidden) Code() int {
	return 403
}

func (o *GetAPIV1BBucketNameEntryNameForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameForbidden", 403)
}

func (o *GetAPIV1BBucketNameEntryNameForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameForbidden", 403)
}

func (o *GetAPIV1BBucketNameEntryNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameNotFound creates a GetAPIV1BBucketNameEntryNameNotFound with default headers values
func NewGetAPIV1BBucketNameEntryNameNotFound() *GetAPIV1BBucketNameEntryNameNotFound {
	return &GetAPIV1BBucketNameEntryNameNotFound{}
}

/*
GetAPIV1BBucketNameEntryNameNotFound describes a response with status code 404, with default header values.

Not Found - The bucket or record with the timestamp not found
*/
type GetAPIV1BBucketNameEntryNameNotFound struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name not found response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name not found response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name not found response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name not found response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name not found response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 b bucket name entry name not found response
func (o *GetAPIV1BBucketNameEntryNameNotFound) Code() int {
	return 404
}

func (o *GetAPIV1BBucketNameEntryNameNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameNotFound", 404)
}

func (o *GetAPIV1BBucketNameEntryNameNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameNotFound", 404)
}

func (o *GetAPIV1BBucketNameEntryNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameUnprocessableEntity creates a GetAPIV1BBucketNameEntryNameUnprocessableEntity with default headers values
func NewGetAPIV1BBucketNameEntryNameUnprocessableEntity() *GetAPIV1BBucketNameEntryNameUnprocessableEntity {
	return &GetAPIV1BBucketNameEntryNameUnprocessableEntity{}
}

/*
GetAPIV1BBucketNameEntryNameUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity - Bad timestamp
*/
type GetAPIV1BBucketNameEntryNameUnprocessableEntity struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name unprocessable entity response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name unprocessable entity response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name unprocessable entity response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name unprocessable entity response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name unprocessable entity response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get Api v1 b bucket name entry name unprocessable entity response
func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) Code() int {
	return 422
}

func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameUnprocessableEntity", 422)
}

func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}][%d] getApiV1BBucketNameEntryNameUnprocessableEntity", 422)
}

func (o *GetAPIV1BBucketNameEntryNameUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
