// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAPIV1BBucketNameEntryNameQReader is a Reader for the GetAPIV1BBucketNameEntryNameQ structure.
type GetAPIV1BBucketNameEntryNameQReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1BBucketNameEntryNameQReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1BBucketNameEntryNameQOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1BBucketNameEntryNameQUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1BBucketNameEntryNameQForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1BBucketNameEntryNameQNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV1BBucketNameEntryNameQUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/b/{bucket_name}/{entry_name}/q] GetAPIV1BBucketNameEntryNameQ", response, response.Code())
	}
}

// NewGetAPIV1BBucketNameEntryNameQOK creates a GetAPIV1BBucketNameEntryNameQOK with default headers values
func NewGetAPIV1BBucketNameEntryNameQOK() *GetAPIV1BBucketNameEntryNameQOK {
	return &GetAPIV1BBucketNameEntryNameQOK{}
}

/*
GetAPIV1BBucketNameEntryNameQOK describes a response with status code 200, with default header values.

Query created successfully
*/
type GetAPIV1BBucketNameEntryNameQOK struct {
	Payload *GetAPIV1BBucketNameEntryNameQOKBody
}

// IsSuccess returns true when this get Api v1 b bucket name entry name q o k response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameQOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 b bucket name entry name q o k response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameQOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name q o k response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameQOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 b bucket name entry name q o k response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameQOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name q o k response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameQOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 b bucket name entry name q o k response
func (o *GetAPIV1BBucketNameEntryNameQOK) Code() int {
	return 200
}

func (o *GetAPIV1BBucketNameEntryNameQOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQOK %s", 200, payload)
}

func (o *GetAPIV1BBucketNameEntryNameQOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQOK %s", 200, payload)
}

func (o *GetAPIV1BBucketNameEntryNameQOK) GetPayload() *GetAPIV1BBucketNameEntryNameQOKBody {
	return o.Payload
}

func (o *GetAPIV1BBucketNameEntryNameQOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAPIV1BBucketNameEntryNameQOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1BBucketNameEntryNameQUnauthorized creates a GetAPIV1BBucketNameEntryNameQUnauthorized with default headers values
func NewGetAPIV1BBucketNameEntryNameQUnauthorized() *GetAPIV1BBucketNameEntryNameQUnauthorized {
	return &GetAPIV1BBucketNameEntryNameQUnauthorized{}
}

/*
GetAPIV1BBucketNameEntryNameQUnauthorized describes a response with status code 401, with default header values.

Unauthorized - Access token is invalid or empty
*/
type GetAPIV1BBucketNameEntryNameQUnauthorized struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name q unauthorized response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name q unauthorized response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name q unauthorized response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name q unauthorized response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name q unauthorized response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 b bucket name entry name q unauthorized response
func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQUnauthorized", 401)
}

func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQUnauthorized", 401)
}

func (o *GetAPIV1BBucketNameEntryNameQUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameQForbidden creates a GetAPIV1BBucketNameEntryNameQForbidden with default headers values
func NewGetAPIV1BBucketNameEntryNameQForbidden() *GetAPIV1BBucketNameEntryNameQForbidden {
	return &GetAPIV1BBucketNameEntryNameQForbidden{}
}

/*
GetAPIV1BBucketNameEntryNameQForbidden describes a response with status code 403, with default header values.

Forbidden - Access token denied
*/
type GetAPIV1BBucketNameEntryNameQForbidden struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name q forbidden response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameQForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name q forbidden response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameQForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name q forbidden response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameQForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name q forbidden response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameQForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name q forbidden response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameQForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 b bucket name entry name q forbidden response
func (o *GetAPIV1BBucketNameEntryNameQForbidden) Code() int {
	return 403
}

func (o *GetAPIV1BBucketNameEntryNameQForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQForbidden", 403)
}

func (o *GetAPIV1BBucketNameEntryNameQForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQForbidden", 403)
}

func (o *GetAPIV1BBucketNameEntryNameQForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameQNotFound creates a GetAPIV1BBucketNameEntryNameQNotFound with default headers values
func NewGetAPIV1BBucketNameEntryNameQNotFound() *GetAPIV1BBucketNameEntryNameQNotFound {
	return &GetAPIV1BBucketNameEntryNameQNotFound{}
}

/*
GetAPIV1BBucketNameEntryNameQNotFound describes a response with status code 404, with default header values.

Not Found - The bucket or entry not found
*/
type GetAPIV1BBucketNameEntryNameQNotFound struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name q not found response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameQNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name q not found response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameQNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name q not found response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameQNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name q not found response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameQNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name q not found response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameQNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 b bucket name entry name q not found response
func (o *GetAPIV1BBucketNameEntryNameQNotFound) Code() int {
	return 404
}

func (o *GetAPIV1BBucketNameEntryNameQNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQNotFound", 404)
}

func (o *GetAPIV1BBucketNameEntryNameQNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQNotFound", 404)
}

func (o *GetAPIV1BBucketNameEntryNameQNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameQUnprocessableEntity creates a GetAPIV1BBucketNameEntryNameQUnprocessableEntity with default headers values
func NewGetAPIV1BBucketNameEntryNameQUnprocessableEntity() *GetAPIV1BBucketNameEntryNameQUnprocessableEntity {
	return &GetAPIV1BBucketNameEntryNameQUnprocessableEntity{}
}

/*
GetAPIV1BBucketNameEntryNameQUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity - Bad timestamp
*/
type GetAPIV1BBucketNameEntryNameQUnprocessableEntity struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name q unprocessable entity response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name q unprocessable entity response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name q unprocessable entity response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name q unprocessable entity response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name q unprocessable entity response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get Api v1 b bucket name entry name q unprocessable entity response
func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) Code() int {
	return 422
}

func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQUnprocessableEntity", 422)
}

func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/q][%d] getApiV1BBucketNameEntryNameQUnprocessableEntity", 422)
}

func (o *GetAPIV1BBucketNameEntryNameQUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
GetAPIV1BBucketNameEntryNameQOKBody get API v1 b bucket name entry name q o k body
swagger:model GetAPIV1BBucketNameEntryNameQOKBody
*/
type GetAPIV1BBucketNameEntryNameQOKBody struct {

	// Query ID
	Q int64 `json:"q,omitempty"`
}

// Validate validates this get API v1 b bucket name entry name q o k body
func (o *GetAPIV1BBucketNameEntryNameQOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get API v1 b bucket name entry name q o k body based on context it is used
func (o *GetAPIV1BBucketNameEntryNameQOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAPIV1BBucketNameEntryNameQOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAPIV1BBucketNameEntryNameQOKBody) UnmarshalBinary(b []byte) error {
	var res GetAPIV1BBucketNameEntryNameQOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
