// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIV1BBucketNameEntryNameBatchReader is a Reader for the GetAPIV1BBucketNameEntryNameBatch structure.
type GetAPIV1BBucketNameEntryNameBatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1BBucketNameEntryNameBatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1BBucketNameEntryNameBatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetAPIV1BBucketNameEntryNameBatchNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1BBucketNameEntryNameBatchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1BBucketNameEntryNameBatchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1BBucketNameEntryNameBatchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAPIV1BBucketNameEntryNameBatchUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/b/{bucket_name}/{entry_name}/batch] GetAPIV1BBucketNameEntryNameBatch", response, response.Code())
	}
}

// NewGetAPIV1BBucketNameEntryNameBatchOK creates a GetAPIV1BBucketNameEntryNameBatchOK with default headers values
func NewGetAPIV1BBucketNameEntryNameBatchOK() *GetAPIV1BBucketNameEntryNameBatchOK {
	return &GetAPIV1BBucketNameEntryNameBatchOK{}
}

/*
GetAPIV1BBucketNameEntryNameBatchOK describes a response with status code 200, with default header values.

The batch of records is found and returned in body of the response
*/
type GetAPIV1BBucketNameEntryNameBatchOK struct {
	Payload string
}

// IsSuccess returns true when this get Api v1 b bucket name entry name batch o k response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 b bucket name entry name batch o k response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name batch o k response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 b bucket name entry name batch o k response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name batch o k response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameBatchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 b bucket name entry name batch o k response
func (o *GetAPIV1BBucketNameEntryNameBatchOK) Code() int {
	return 200
}

func (o *GetAPIV1BBucketNameEntryNameBatchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchOK %s", 200, payload)
}

func (o *GetAPIV1BBucketNameEntryNameBatchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchOK %s", 200, payload)
}

func (o *GetAPIV1BBucketNameEntryNameBatchOK) GetPayload() string {
	return o.Payload
}

func (o *GetAPIV1BBucketNameEntryNameBatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1BBucketNameEntryNameBatchNoContent creates a GetAPIV1BBucketNameEntryNameBatchNoContent with default headers values
func NewGetAPIV1BBucketNameEntryNameBatchNoContent() *GetAPIV1BBucketNameEntryNameBatchNoContent {
	return &GetAPIV1BBucketNameEntryNameBatchNoContent{}
}

/*
GetAPIV1BBucketNameEntryNameBatchNoContent describes a response with status code 204, with default header values.

No Content - If there is no record available for the given query
*/
type GetAPIV1BBucketNameEntryNameBatchNoContent struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name batch no content response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 b bucket name entry name batch no content response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name batch no content response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 b bucket name entry name batch no content response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name batch no content response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get Api v1 b bucket name entry name batch no content response
func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) Code() int {
	return 204
}

func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchNoContent", 204)
}

func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchNoContent", 204)
}

func (o *GetAPIV1BBucketNameEntryNameBatchNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameBatchUnauthorized creates a GetAPIV1BBucketNameEntryNameBatchUnauthorized with default headers values
func NewGetAPIV1BBucketNameEntryNameBatchUnauthorized() *GetAPIV1BBucketNameEntryNameBatchUnauthorized {
	return &GetAPIV1BBucketNameEntryNameBatchUnauthorized{}
}

/*
GetAPIV1BBucketNameEntryNameBatchUnauthorized describes a response with status code 401, with default header values.

Unauthorized - Access token is invalid or empty
*/
type GetAPIV1BBucketNameEntryNameBatchUnauthorized struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name batch unauthorized response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name batch unauthorized response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name batch unauthorized response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name batch unauthorized response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name batch unauthorized response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 b bucket name entry name batch unauthorized response
func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchUnauthorized", 401)
}

func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchUnauthorized", 401)
}

func (o *GetAPIV1BBucketNameEntryNameBatchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameBatchForbidden creates a GetAPIV1BBucketNameEntryNameBatchForbidden with default headers values
func NewGetAPIV1BBucketNameEntryNameBatchForbidden() *GetAPIV1BBucketNameEntryNameBatchForbidden {
	return &GetAPIV1BBucketNameEntryNameBatchForbidden{}
}

/*
GetAPIV1BBucketNameEntryNameBatchForbidden describes a response with status code 403, with default header values.

Forbidden - Access token denied
*/
type GetAPIV1BBucketNameEntryNameBatchForbidden struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name batch forbidden response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name batch forbidden response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name batch forbidden response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name batch forbidden response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name batch forbidden response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 b bucket name entry name batch forbidden response
func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) Code() int {
	return 403
}

func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchForbidden", 403)
}

func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchForbidden", 403)
}

func (o *GetAPIV1BBucketNameEntryNameBatchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameBatchNotFound creates a GetAPIV1BBucketNameEntryNameBatchNotFound with default headers values
func NewGetAPIV1BBucketNameEntryNameBatchNotFound() *GetAPIV1BBucketNameEntryNameBatchNotFound {
	return &GetAPIV1BBucketNameEntryNameBatchNotFound{}
}

/*
GetAPIV1BBucketNameEntryNameBatchNotFound describes a response with status code 404, with default header values.

Not Found - The bucket or record not found
*/
type GetAPIV1BBucketNameEntryNameBatchNotFound struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name batch not found response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name batch not found response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name batch not found response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name batch not found response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name batch not found response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 b bucket name entry name batch not found response
func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) Code() int {
	return 404
}

func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchNotFound", 404)
}

func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchNotFound", 404)
}

func (o *GetAPIV1BBucketNameEntryNameBatchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV1BBucketNameEntryNameBatchUnprocessableEntity creates a GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity with default headers values
func NewGetAPIV1BBucketNameEntryNameBatchUnprocessableEntity() *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity {
	return &GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity{}
}

/*
GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity - Bad timestamp
*/
type GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity struct {
}

// IsSuccess returns true when this get Api v1 b bucket name entry name batch unprocessable entity response has a 2xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 b bucket name entry name batch unprocessable entity response has a 3xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 b bucket name entry name batch unprocessable entity response has a 4xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 b bucket name entry name batch unprocessable entity response has a 5xx status code
func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 b bucket name entry name batch unprocessable entity response a status code equal to that given
func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get Api v1 b bucket name entry name batch unprocessable entity response
func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) Code() int {
	return 422
}

func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchUnprocessableEntity", 422)
}

func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v1/b/{bucket_name}/{entry_name}/batch][%d] getApiV1BBucketNameEntryNameBatchUnprocessableEntity", 422)
}

func (o *GetAPIV1BBucketNameEntryNameBatchUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
