// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1BBucketNameEntryNameParams creates a new GetAPIV1BBucketNameEntryNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1BBucketNameEntryNameParams() *GetAPIV1BBucketNameEntryNameParams {
	return &GetAPIV1BBucketNameEntryNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1BBucketNameEntryNameParamsWithTimeout creates a new GetAPIV1BBucketNameEntryNameParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1BBucketNameEntryNameParamsWithTimeout(timeout time.Duration) *GetAPIV1BBucketNameEntryNameParams {
	return &GetAPIV1BBucketNameEntryNameParams{
		timeout: timeout,
	}
}

// NewGetAPIV1BBucketNameEntryNameParamsWithContext creates a new GetAPIV1BBucketNameEntryNameParams object
// with the ability to set a context for a request.
func NewGetAPIV1BBucketNameEntryNameParamsWithContext(ctx context.Context) *GetAPIV1BBucketNameEntryNameParams {
	return &GetAPIV1BBucketNameEntryNameParams{
		Context: ctx,
	}
}

// NewGetAPIV1BBucketNameEntryNameParamsWithHTTPClient creates a new GetAPIV1BBucketNameEntryNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1BBucketNameEntryNameParamsWithHTTPClient(client *http.Client) *GetAPIV1BBucketNameEntryNameParams {
	return &GetAPIV1BBucketNameEntryNameParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1BBucketNameEntryNameParams contains all the parameters to send to the API endpoint

	for the get API v1 b bucket name entry name operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1BBucketNameEntryNameParams struct {

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	/* EntryName.

	   Name of entry
	*/
	EntryName string

	/* Q.

	   A query ID to read the next record in the query. If it is set, the `ts` parameter is ignored.
	*/
	Q *string

	/* Ts.

	   A UNIX timestamp in microseconds. If it is empty, the latest record is returned.

	   Format: int64
	*/
	Ts *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 b bucket name entry name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1BBucketNameEntryNameParams) WithDefaults() *GetAPIV1BBucketNameEntryNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 b bucket name entry name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1BBucketNameEntryNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithTimeout(timeout time.Duration) *GetAPIV1BBucketNameEntryNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithContext(ctx context.Context) *GetAPIV1BBucketNameEntryNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithHTTPClient(client *http.Client) *GetAPIV1BBucketNameEntryNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketName adds the bucketName to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithBucketName(bucketName string) *GetAPIV1BBucketNameEntryNameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WithEntryName adds the entryName to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithEntryName(entryName string) *GetAPIV1BBucketNameEntryNameParams {
	o.SetEntryName(entryName)
	return o
}

// SetEntryName adds the entryName to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetEntryName(entryName string) {
	o.EntryName = entryName
}

// WithQ adds the q to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithQ(q *string) *GetAPIV1BBucketNameEntryNameParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetQ(q *string) {
	o.Q = q
}

// WithTs adds the ts to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) WithTs(ts *int64) *GetAPIV1BBucketNameEntryNameParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get API v1 b bucket name entry name params
func (o *GetAPIV1BBucketNameEntryNameParams) SetTs(ts *int64) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1BBucketNameEntryNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	// path param entry_name
	if err := r.SetPathParam("entry_name", o.EntryName); err != nil {
		return err
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Ts != nil {

		// query param ts
		var qrTs int64

		if o.Ts != nil {
			qrTs = *o.Ts
		}
		qTs := swag.FormatInt64(qrTs)
		if qTs != "" {

			if err := r.SetQueryParam("ts", qTs); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
