// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1BBucketNameParams creates a new GetAPIV1BBucketNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1BBucketNameParams() *GetAPIV1BBucketNameParams {
	return &GetAPIV1BBucketNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1BBucketNameParamsWithTimeout creates a new GetAPIV1BBucketNameParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1BBucketNameParamsWithTimeout(timeout time.Duration) *GetAPIV1BBucketNameParams {
	return &GetAPIV1BBucketNameParams{
		timeout: timeout,
	}
}

// NewGetAPIV1BBucketNameParamsWithContext creates a new GetAPIV1BBucketNameParams object
// with the ability to set a context for a request.
func NewGetAPIV1BBucketNameParamsWithContext(ctx context.Context) *GetAPIV1BBucketNameParams {
	return &GetAPIV1BBucketNameParams{
		Context: ctx,
	}
}

// NewGetAPIV1BBucketNameParamsWithHTTPClient creates a new GetAPIV1BBucketNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1BBucketNameParamsWithHTTPClient(client *http.Client) *GetAPIV1BBucketNameParams {
	return &GetAPIV1BBucketNameParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1BBucketNameParams contains all the parameters to send to the API endpoint

	for the get API v1 b bucket name operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1BBucketNameParams struct {

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1BBucketNameParams) WithDefaults() *GetAPIV1BBucketNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1BBucketNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) WithTimeout(timeout time.Duration) *GetAPIV1BBucketNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) WithContext(ctx context.Context) *GetAPIV1BBucketNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) WithHTTPClient(client *http.Client) *GetAPIV1BBucketNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketName adds the bucketName to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) WithBucketName(bucketName string) *GetAPIV1BBucketNameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the get API v1 b bucket name params
func (o *GetAPIV1BBucketNameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1BBucketNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
