// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1BBucketNameEntryNameBatchParams creates a new GetAPIV1BBucketNameEntryNameBatchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1BBucketNameEntryNameBatchParams() *GetAPIV1BBucketNameEntryNameBatchParams {
	return &GetAPIV1BBucketNameEntryNameBatchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1BBucketNameEntryNameBatchParamsWithTimeout creates a new GetAPIV1BBucketNameEntryNameBatchParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1BBucketNameEntryNameBatchParamsWithTimeout(timeout time.Duration) *GetAPIV1BBucketNameEntryNameBatchParams {
	return &GetAPIV1BBucketNameEntryNameBatchParams{
		timeout: timeout,
	}
}

// NewGetAPIV1BBucketNameEntryNameBatchParamsWithContext creates a new GetAPIV1BBucketNameEntryNameBatchParams object
// with the ability to set a context for a request.
func NewGetAPIV1BBucketNameEntryNameBatchParamsWithContext(ctx context.Context) *GetAPIV1BBucketNameEntryNameBatchParams {
	return &GetAPIV1BBucketNameEntryNameBatchParams{
		Context: ctx,
	}
}

// NewGetAPIV1BBucketNameEntryNameBatchParamsWithHTTPClient creates a new GetAPIV1BBucketNameEntryNameBatchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1BBucketNameEntryNameBatchParamsWithHTTPClient(client *http.Client) *GetAPIV1BBucketNameEntryNameBatchParams {
	return &GetAPIV1BBucketNameEntryNameBatchParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1BBucketNameEntryNameBatchParams contains all the parameters to send to the API endpoint

	for the get API v1 b bucket name entry name batch operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1BBucketNameEntryNameBatchParams struct {

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	/* EntryName.

	   Name of entry
	*/
	EntryName string

	/* Q.

	   A query ID to read the next record in the query
	*/
	Q int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 b bucket name entry name batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithDefaults() *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 b bucket name entry name batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithTimeout(timeout time.Duration) *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithContext(ctx context.Context) *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithHTTPClient(client *http.Client) *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketName adds the bucketName to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithBucketName(bucketName string) *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WithEntryName adds the entryName to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithEntryName(entryName string) *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetEntryName(entryName)
	return o
}

// SetEntryName adds the entryName to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetEntryName(entryName string) {
	o.EntryName = entryName
}

// WithQ adds the q to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WithQ(q int64) *GetAPIV1BBucketNameEntryNameBatchParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the get API v1 b bucket name entry name batch params
func (o *GetAPIV1BBucketNameEntryNameBatchParams) SetQ(q int64) {
	o.Q = q
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1BBucketNameEntryNameBatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	// path param entry_name
	if err := r.SetPathParam("entry_name", o.EntryName); err != nil {
		return err
	}

	// query param q
	qrQ := o.Q
	qQ := swag.FormatInt64(qrQ)
	if qQ != "" {

		if err := r.SetQueryParam("q", qQ); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
