// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHeadAPIV1BBucketNameParams creates a new HeadAPIV1BBucketNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHeadAPIV1BBucketNameParams() *HeadAPIV1BBucketNameParams {
	return &HeadAPIV1BBucketNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHeadAPIV1BBucketNameParamsWithTimeout creates a new HeadAPIV1BBucketNameParams object
// with the ability to set a timeout on a request.
func NewHeadAPIV1BBucketNameParamsWithTimeout(timeout time.Duration) *HeadAPIV1BBucketNameParams {
	return &HeadAPIV1BBucketNameParams{
		timeout: timeout,
	}
}

// NewHeadAPIV1BBucketNameParamsWithContext creates a new HeadAPIV1BBucketNameParams object
// with the ability to set a context for a request.
func NewHeadAPIV1BBucketNameParamsWithContext(ctx context.Context) *HeadAPIV1BBucketNameParams {
	return &HeadAPIV1BBucketNameParams{
		Context: ctx,
	}
}

// NewHeadAPIV1BBucketNameParamsWithHTTPClient creates a new HeadAPIV1BBucketNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewHeadAPIV1BBucketNameParamsWithHTTPClient(client *http.Client) *HeadAPIV1BBucketNameParams {
	return &HeadAPIV1BBucketNameParams{
		HTTPClient: client,
	}
}

/*
HeadAPIV1BBucketNameParams contains all the parameters to send to the API endpoint

	for the head API v1 b bucket name operation.

	Typically these are written to a http.Request.
*/
type HeadAPIV1BBucketNameParams struct {

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the head API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV1BBucketNameParams) WithDefaults() *HeadAPIV1BBucketNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the head API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV1BBucketNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) WithTimeout(timeout time.Duration) *HeadAPIV1BBucketNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) WithContext(ctx context.Context) *HeadAPIV1BBucketNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) WithHTTPClient(client *http.Client) *HeadAPIV1BBucketNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketName adds the bucketName to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) WithBucketName(bucketName string) *HeadAPIV1BBucketNameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the head API v1 b bucket name params
func (o *HeadAPIV1BBucketNameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WriteToRequest writes these params to a swagger request
func (o *HeadAPIV1BBucketNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
