// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPIV1BBucketNameEntryNameBatchReader is a Reader for the PostAPIV1BBucketNameEntryNameBatch structure.
type PostAPIV1BBucketNameEntryNameBatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1BBucketNameEntryNameBatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1BBucketNameEntryNameBatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1BBucketNameEntryNameBatchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1BBucketNameEntryNameBatchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1BBucketNameEntryNameBatchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1BBucketNameEntryNameBatchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV1BBucketNameEntryNameBatchUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/b/{bucket_name}/{entry_name}/batch] PostAPIV1BBucketNameEntryNameBatch", response, response.Code())
	}
}

// NewPostAPIV1BBucketNameEntryNameBatchOK creates a PostAPIV1BBucketNameEntryNameBatchOK with default headers values
func NewPostAPIV1BBucketNameEntryNameBatchOK() *PostAPIV1BBucketNameEntryNameBatchOK {
	return &PostAPIV1BBucketNameEntryNameBatchOK{}
}

/*
PostAPIV1BBucketNameEntryNameBatchOK describes a response with status code 200, with default header values.

The request was valid. However, some records may not be written. Check headers.
*/
type PostAPIV1BBucketNameEntryNameBatchOK struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name batch o k response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 b bucket name entry name batch o k response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name batch o k response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 b bucket name entry name batch o k response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name batch o k response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBatchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 b bucket name entry name batch o k response
func (o *PostAPIV1BBucketNameEntryNameBatchOK) Code() int {
	return 200
}

func (o *PostAPIV1BBucketNameEntryNameBatchOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchOK", 200)
}

func (o *PostAPIV1BBucketNameEntryNameBatchOK) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchOK", 200)
}

func (o *PostAPIV1BBucketNameEntryNameBatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameBatchBadRequest creates a PostAPIV1BBucketNameEntryNameBatchBadRequest with default headers values
func NewPostAPIV1BBucketNameEntryNameBatchBadRequest() *PostAPIV1BBucketNameEntryNameBatchBadRequest {
	return &PostAPIV1BBucketNameEntryNameBatchBadRequest{}
}

/*
PostAPIV1BBucketNameEntryNameBatchBadRequest describes a response with status code 400, with default header values.

Posted content bigger or smaller than content-length
*/
type PostAPIV1BBucketNameEntryNameBatchBadRequest struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name batch bad request response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name batch bad request response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name batch bad request response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name batch bad request response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name batch bad request response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 b bucket name entry name batch bad request response
func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchBadRequest", 400)
}

func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchBadRequest", 400)
}

func (o *PostAPIV1BBucketNameEntryNameBatchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameBatchUnauthorized creates a PostAPIV1BBucketNameEntryNameBatchUnauthorized with default headers values
func NewPostAPIV1BBucketNameEntryNameBatchUnauthorized() *PostAPIV1BBucketNameEntryNameBatchUnauthorized {
	return &PostAPIV1BBucketNameEntryNameBatchUnauthorized{}
}

/*
PostAPIV1BBucketNameEntryNameBatchUnauthorized describes a response with status code 401, with default header values.

Access token is invalid or empty
*/
type PostAPIV1BBucketNameEntryNameBatchUnauthorized struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name batch unauthorized response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name batch unauthorized response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name batch unauthorized response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name batch unauthorized response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name batch unauthorized response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 b bucket name entry name batch unauthorized response
func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchUnauthorized", 401)
}

func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchUnauthorized", 401)
}

func (o *PostAPIV1BBucketNameEntryNameBatchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameBatchForbidden creates a PostAPIV1BBucketNameEntryNameBatchForbidden with default headers values
func NewPostAPIV1BBucketNameEntryNameBatchForbidden() *PostAPIV1BBucketNameEntryNameBatchForbidden {
	return &PostAPIV1BBucketNameEntryNameBatchForbidden{}
}

/*
PostAPIV1BBucketNameEntryNameBatchForbidden describes a response with status code 403, with default header values.

Access token does not have write permissions
*/
type PostAPIV1BBucketNameEntryNameBatchForbidden struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name batch forbidden response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name batch forbidden response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name batch forbidden response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name batch forbidden response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name batch forbidden response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 b bucket name entry name batch forbidden response
func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) Code() int {
	return 403
}

func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchForbidden", 403)
}

func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchForbidden", 403)
}

func (o *PostAPIV1BBucketNameEntryNameBatchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameBatchNotFound creates a PostAPIV1BBucketNameEntryNameBatchNotFound with default headers values
func NewPostAPIV1BBucketNameEntryNameBatchNotFound() *PostAPIV1BBucketNameEntryNameBatchNotFound {
	return &PostAPIV1BBucketNameEntryNameBatchNotFound{}
}

/*
PostAPIV1BBucketNameEntryNameBatchNotFound describes a response with status code 404, with default header values.

Bucket is not found
*/
type PostAPIV1BBucketNameEntryNameBatchNotFound struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name batch not found response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name batch not found response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name batch not found response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name batch not found response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name batch not found response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 b bucket name entry name batch not found response
func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) Code() int {
	return 404
}

func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchNotFound", 404)
}

func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchNotFound", 404)
}

func (o *PostAPIV1BBucketNameEntryNameBatchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameBatchUnprocessableEntity creates a PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity with default headers values
func NewPostAPIV1BBucketNameEntryNameBatchUnprocessableEntity() *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity {
	return &PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity{}
}

/*
PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity describes a response with status code 422, with default header values.

Bad timestamp or header format
*/
type PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name batch unprocessable entity response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name batch unprocessable entity response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name batch unprocessable entity response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name batch unprocessable entity response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name batch unprocessable entity response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the post Api v1 b bucket name entry name batch unprocessable entity response
func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) Code() int {
	return 422
}

func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchUnprocessableEntity", 422)
}

func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}/batch][%d] postApiV1BBucketNameEntryNameBatchUnprocessableEntity", 422)
}

func (o *PostAPIV1BBucketNameEntryNameBatchUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
