// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPIV1BBucketNameEntryNameReader is a Reader for the PostAPIV1BBucketNameEntryName structure.
type PostAPIV1BBucketNameEntryNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1BBucketNameEntryNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1BBucketNameEntryNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1BBucketNameEntryNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1BBucketNameEntryNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1BBucketNameEntryNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1BBucketNameEntryNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1BBucketNameEntryNameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV1BBucketNameEntryNameUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/b/{bucket_name}/{entry_name}] PostAPIV1BBucketNameEntryName", response, response.Code())
	}
}

// NewPostAPIV1BBucketNameEntryNameOK creates a PostAPIV1BBucketNameEntryNameOK with default headers values
func NewPostAPIV1BBucketNameEntryNameOK() *PostAPIV1BBucketNameEntryNameOK {
	return &PostAPIV1BBucketNameEntryNameOK{}
}

/*
PostAPIV1BBucketNameEntryNameOK describes a response with status code 200, with default header values.

The record is written
*/
type PostAPIV1BBucketNameEntryNameOK struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name o k response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 b bucket name entry name o k response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name o k response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 b bucket name entry name o k response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name o k response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 b bucket name entry name o k response
func (o *PostAPIV1BBucketNameEntryNameOK) Code() int {
	return 200
}

func (o *PostAPIV1BBucketNameEntryNameOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameOK", 200)
}

func (o *PostAPIV1BBucketNameEntryNameOK) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameOK", 200)
}

func (o *PostAPIV1BBucketNameEntryNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameBadRequest creates a PostAPIV1BBucketNameEntryNameBadRequest with default headers values
func NewPostAPIV1BBucketNameEntryNameBadRequest() *PostAPIV1BBucketNameEntryNameBadRequest {
	return &PostAPIV1BBucketNameEntryNameBadRequest{}
}

/*
PostAPIV1BBucketNameEntryNameBadRequest describes a response with status code 400, with default header values.

Posted content bigger or smaller than content-length
*/
type PostAPIV1BBucketNameEntryNameBadRequest struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name bad request response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name bad request response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name bad request response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name bad request response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name bad request response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 b bucket name entry name bad request response
func (o *PostAPIV1BBucketNameEntryNameBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1BBucketNameEntryNameBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameBadRequest", 400)
}

func (o *PostAPIV1BBucketNameEntryNameBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameBadRequest", 400)
}

func (o *PostAPIV1BBucketNameEntryNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameUnauthorized creates a PostAPIV1BBucketNameEntryNameUnauthorized with default headers values
func NewPostAPIV1BBucketNameEntryNameUnauthorized() *PostAPIV1BBucketNameEntryNameUnauthorized {
	return &PostAPIV1BBucketNameEntryNameUnauthorized{}
}

/*
PostAPIV1BBucketNameEntryNameUnauthorized describes a response with status code 401, with default header values.

Access token is invalid or empty
*/
type PostAPIV1BBucketNameEntryNameUnauthorized struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name unauthorized response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name unauthorized response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name unauthorized response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name unauthorized response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name unauthorized response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 b bucket name entry name unauthorized response
func (o *PostAPIV1BBucketNameEntryNameUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1BBucketNameEntryNameUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameUnauthorized", 401)
}

func (o *PostAPIV1BBucketNameEntryNameUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameUnauthorized", 401)
}

func (o *PostAPIV1BBucketNameEntryNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameForbidden creates a PostAPIV1BBucketNameEntryNameForbidden with default headers values
func NewPostAPIV1BBucketNameEntryNameForbidden() *PostAPIV1BBucketNameEntryNameForbidden {
	return &PostAPIV1BBucketNameEntryNameForbidden{}
}

/*
PostAPIV1BBucketNameEntryNameForbidden describes a response with status code 403, with default header values.

Access token does not have write permissions
*/
type PostAPIV1BBucketNameEntryNameForbidden struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name forbidden response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name forbidden response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name forbidden response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name forbidden response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name forbidden response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 b bucket name entry name forbidden response
func (o *PostAPIV1BBucketNameEntryNameForbidden) Code() int {
	return 403
}

func (o *PostAPIV1BBucketNameEntryNameForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameForbidden", 403)
}

func (o *PostAPIV1BBucketNameEntryNameForbidden) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameForbidden", 403)
}

func (o *PostAPIV1BBucketNameEntryNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameNotFound creates a PostAPIV1BBucketNameEntryNameNotFound with default headers values
func NewPostAPIV1BBucketNameEntryNameNotFound() *PostAPIV1BBucketNameEntryNameNotFound {
	return &PostAPIV1BBucketNameEntryNameNotFound{}
}

/*
PostAPIV1BBucketNameEntryNameNotFound describes a response with status code 404, with default header values.

Bucket is not found
*/
type PostAPIV1BBucketNameEntryNameNotFound struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name not found response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name not found response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name not found response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name not found response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name not found response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 b bucket name entry name not found response
func (o *PostAPIV1BBucketNameEntryNameNotFound) Code() int {
	return 404
}

func (o *PostAPIV1BBucketNameEntryNameNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameNotFound", 404)
}

func (o *PostAPIV1BBucketNameEntryNameNotFound) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameNotFound", 404)
}

func (o *PostAPIV1BBucketNameEntryNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameConflict creates a PostAPIV1BBucketNameEntryNameConflict with default headers values
func NewPostAPIV1BBucketNameEntryNameConflict() *PostAPIV1BBucketNameEntryNameConflict {
	return &PostAPIV1BBucketNameEntryNameConflict{}
}

/*
PostAPIV1BBucketNameEntryNameConflict describes a response with status code 409, with default header values.

A record with the same timestamp already exists
*/
type PostAPIV1BBucketNameEntryNameConflict struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name conflict response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name conflict response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name conflict response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name conflict response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name conflict response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 b bucket name entry name conflict response
func (o *PostAPIV1BBucketNameEntryNameConflict) Code() int {
	return 409
}

func (o *PostAPIV1BBucketNameEntryNameConflict) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameConflict", 409)
}

func (o *PostAPIV1BBucketNameEntryNameConflict) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameConflict", 409)
}

func (o *PostAPIV1BBucketNameEntryNameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameEntryNameUnprocessableEntity creates a PostAPIV1BBucketNameEntryNameUnprocessableEntity with default headers values
func NewPostAPIV1BBucketNameEntryNameUnprocessableEntity() *PostAPIV1BBucketNameEntryNameUnprocessableEntity {
	return &PostAPIV1BBucketNameEntryNameUnprocessableEntity{}
}

/*
PostAPIV1BBucketNameEntryNameUnprocessableEntity describes a response with status code 422, with default header values.

Bad timestamp
*/
type PostAPIV1BBucketNameEntryNameUnprocessableEntity struct {
}

// IsSuccess returns true when this post Api v1 b bucket name entry name unprocessable entity response has a 2xx status code
func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name entry name unprocessable entity response has a 3xx status code
func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name entry name unprocessable entity response has a 4xx status code
func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name entry name unprocessable entity response has a 5xx status code
func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name entry name unprocessable entity response a status code equal to that given
func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the post Api v1 b bucket name entry name unprocessable entity response
func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) Code() int {
	return 422
}

func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameUnprocessableEntity", 422)
}

func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}/{entry_name}][%d] postApiV1BBucketNameEntryNameUnprocessableEntity", 422)
}

func (o *PostAPIV1BBucketNameEntryNameUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
