// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostAPIV1BBucketNameEntryNameParams creates a new PostAPIV1BBucketNameEntryNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1BBucketNameEntryNameParams() *PostAPIV1BBucketNameEntryNameParams {
	return &PostAPIV1BBucketNameEntryNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1BBucketNameEntryNameParamsWithTimeout creates a new PostAPIV1BBucketNameEntryNameParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1BBucketNameEntryNameParamsWithTimeout(timeout time.Duration) *PostAPIV1BBucketNameEntryNameParams {
	return &PostAPIV1BBucketNameEntryNameParams{
		timeout: timeout,
	}
}

// NewPostAPIV1BBucketNameEntryNameParamsWithContext creates a new PostAPIV1BBucketNameEntryNameParams object
// with the ability to set a context for a request.
func NewPostAPIV1BBucketNameEntryNameParamsWithContext(ctx context.Context) *PostAPIV1BBucketNameEntryNameParams {
	return &PostAPIV1BBucketNameEntryNameParams{
		Context: ctx,
	}
}

// NewPostAPIV1BBucketNameEntryNameParamsWithHTTPClient creates a new PostAPIV1BBucketNameEntryNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1BBucketNameEntryNameParamsWithHTTPClient(client *http.Client) *PostAPIV1BBucketNameEntryNameParams {
	return &PostAPIV1BBucketNameEntryNameParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1BBucketNameEntryNameParams contains all the parameters to send to the API endpoint

	for the post API v1 b bucket name entry name operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1BBucketNameEntryNameParams struct {

	/* ContentLength.

	   Content-length is required to start an asynchronous write operation

	   Format: int64
	*/
	ContentLength int64

	/* Body.

	   Record payload (can be empty)

	   Format: binary
	*/
	Body io.ReadCloser

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	/* EntryName.

	   Name of entry
	*/
	EntryName string

	/* Ts.

	   A UNIX timestamp in microseconds

	   Format: int64
	*/
	Ts int64

	/* XReductLabelName.

	   A value of a label assigned to the record
	*/
	XReductLabelName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 b bucket name entry name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1BBucketNameEntryNameParams) WithDefaults() *PostAPIV1BBucketNameEntryNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 b bucket name entry name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1BBucketNameEntryNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithTimeout(timeout time.Duration) *PostAPIV1BBucketNameEntryNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithContext(ctx context.Context) *PostAPIV1BBucketNameEntryNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithHTTPClient(client *http.Client) *PostAPIV1BBucketNameEntryNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentLength adds the contentLength to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithContentLength(contentLength int64) *PostAPIV1BBucketNameEntryNameParams {
	o.SetContentLength(contentLength)
	return o
}

// SetContentLength adds the contentLength to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetContentLength(contentLength int64) {
	o.ContentLength = contentLength
}

// WithBody adds the body to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithBody(body io.ReadCloser) *PostAPIV1BBucketNameEntryNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetBody(body io.ReadCloser) {
	o.Body = body
}

// WithBucketName adds the bucketName to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithBucketName(bucketName string) *PostAPIV1BBucketNameEntryNameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WithEntryName adds the entryName to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithEntryName(entryName string) *PostAPIV1BBucketNameEntryNameParams {
	o.SetEntryName(entryName)
	return o
}

// SetEntryName adds the entryName to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetEntryName(entryName string) {
	o.EntryName = entryName
}

// WithTs adds the ts to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithTs(ts int64) *PostAPIV1BBucketNameEntryNameParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetTs(ts int64) {
	o.Ts = ts
}

// WithXReductLabelName adds the xReductLabelName to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) WithXReductLabelName(xReductLabelName *string) *PostAPIV1BBucketNameEntryNameParams {
	o.SetXReductLabelName(xReductLabelName)
	return o
}

// SetXReductLabelName adds the xReductLabelName to the post API v1 b bucket name entry name params
func (o *PostAPIV1BBucketNameEntryNameParams) SetXReductLabelName(xReductLabelName *string) {
	o.XReductLabelName = xReductLabelName
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1BBucketNameEntryNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Length
	if err := r.SetHeaderParam("Content-Length", swag.FormatInt64(o.ContentLength)); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	// path param entry_name
	if err := r.SetPathParam("entry_name", o.EntryName); err != nil {
		return err
	}

	// query param ts
	qrTs := o.Ts
	qTs := swag.FormatInt64(qrTs)
	if qTs != "" {

		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if o.XReductLabelName != nil {

		// header param x-reduct-label-<name>
		if err := r.SetHeaderParam("x-reduct-label-<name>", *o.XReductLabelName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
