// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1BBucketNameParams creates a new PostAPIV1BBucketNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1BBucketNameParams() *PostAPIV1BBucketNameParams {
	return &PostAPIV1BBucketNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1BBucketNameParamsWithTimeout creates a new PostAPIV1BBucketNameParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1BBucketNameParamsWithTimeout(timeout time.Duration) *PostAPIV1BBucketNameParams {
	return &PostAPIV1BBucketNameParams{
		timeout: timeout,
	}
}

// NewPostAPIV1BBucketNameParamsWithContext creates a new PostAPIV1BBucketNameParams object
// with the ability to set a context for a request.
func NewPostAPIV1BBucketNameParamsWithContext(ctx context.Context) *PostAPIV1BBucketNameParams {
	return &PostAPIV1BBucketNameParams{
		Context: ctx,
	}
}

// NewPostAPIV1BBucketNameParamsWithHTTPClient creates a new PostAPIV1BBucketNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1BBucketNameParamsWithHTTPClient(client *http.Client) *PostAPIV1BBucketNameParams {
	return &PostAPIV1BBucketNameParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1BBucketNameParams contains all the parameters to send to the API endpoint

	for the post API v1 b bucket name operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1BBucketNameParams struct {

	/* Body.

	   Parameters for creating a bucket
	*/
	Body PostAPIV1BBucketNameBody

	/* BucketName.

	   Name of new bucket
	*/
	BucketName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1BBucketNameParams) WithDefaults() *PostAPIV1BBucketNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1BBucketNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) WithTimeout(timeout time.Duration) *PostAPIV1BBucketNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) WithContext(ctx context.Context) *PostAPIV1BBucketNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) WithHTTPClient(client *http.Client) *PostAPIV1BBucketNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) WithBody(body PostAPIV1BBucketNameBody) *PostAPIV1BBucketNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) SetBody(body PostAPIV1BBucketNameBody) {
	o.Body = body
}

// WithBucketName adds the bucketName to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) WithBucketName(bucketName string) *PostAPIV1BBucketNameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the post API v1 b bucket name params
func (o *PostAPIV1BBucketNameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1BBucketNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
