// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostAPIV1BBucketNameReader is a Reader for the PostAPIV1BBucketName structure.
type PostAPIV1BBucketNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1BBucketNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1BBucketNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostAPIV1BBucketNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1BBucketNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1BBucketNameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostAPIV1BBucketNameUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/b/{bucket_name}] PostAPIV1BBucketName", response, response.Code())
	}
}

// NewPostAPIV1BBucketNameOK creates a PostAPIV1BBucketNameOK with default headers values
func NewPostAPIV1BBucketNameOK() *PostAPIV1BBucketNameOK {
	return &PostAPIV1BBucketNameOK{}
}

/*
PostAPIV1BBucketNameOK describes a response with status code 200, with default header values.

The new bucket is created
*/
type PostAPIV1BBucketNameOK struct {
}

// IsSuccess returns true when this post Api v1 b bucket name o k response has a 2xx status code
func (o *PostAPIV1BBucketNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 b bucket name o k response has a 3xx status code
func (o *PostAPIV1BBucketNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name o k response has a 4xx status code
func (o *PostAPIV1BBucketNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 b bucket name o k response has a 5xx status code
func (o *PostAPIV1BBucketNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name o k response a status code equal to that given
func (o *PostAPIV1BBucketNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 b bucket name o k response
func (o *PostAPIV1BBucketNameOK) Code() int {
	return 200
}

func (o *PostAPIV1BBucketNameOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameOK", 200)
}

func (o *PostAPIV1BBucketNameOK) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameOK", 200)
}

func (o *PostAPIV1BBucketNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameUnauthorized creates a PostAPIV1BBucketNameUnauthorized with default headers values
func NewPostAPIV1BBucketNameUnauthorized() *PostAPIV1BBucketNameUnauthorized {
	return &PostAPIV1BBucketNameUnauthorized{}
}

/*
PostAPIV1BBucketNameUnauthorized describes a response with status code 401, with default header values.

Access token is invalid or empty
*/
type PostAPIV1BBucketNameUnauthorized struct {
}

// IsSuccess returns true when this post Api v1 b bucket name unauthorized response has a 2xx status code
func (o *PostAPIV1BBucketNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name unauthorized response has a 3xx status code
func (o *PostAPIV1BBucketNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name unauthorized response has a 4xx status code
func (o *PostAPIV1BBucketNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name unauthorized response has a 5xx status code
func (o *PostAPIV1BBucketNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name unauthorized response a status code equal to that given
func (o *PostAPIV1BBucketNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 b bucket name unauthorized response
func (o *PostAPIV1BBucketNameUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1BBucketNameUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameUnauthorized", 401)
}

func (o *PostAPIV1BBucketNameUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameUnauthorized", 401)
}

func (o *PostAPIV1BBucketNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameForbidden creates a PostAPIV1BBucketNameForbidden with default headers values
func NewPostAPIV1BBucketNameForbidden() *PostAPIV1BBucketNameForbidden {
	return &PostAPIV1BBucketNameForbidden{}
}

/*
PostAPIV1BBucketNameForbidden describes a response with status code 403, with default header values.

Access token doesn't have enough permissions
*/
type PostAPIV1BBucketNameForbidden struct {
}

// IsSuccess returns true when this post Api v1 b bucket name forbidden response has a 2xx status code
func (o *PostAPIV1BBucketNameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name forbidden response has a 3xx status code
func (o *PostAPIV1BBucketNameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name forbidden response has a 4xx status code
func (o *PostAPIV1BBucketNameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name forbidden response has a 5xx status code
func (o *PostAPIV1BBucketNameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name forbidden response a status code equal to that given
func (o *PostAPIV1BBucketNameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 b bucket name forbidden response
func (o *PostAPIV1BBucketNameForbidden) Code() int {
	return 403
}

func (o *PostAPIV1BBucketNameForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameForbidden", 403)
}

func (o *PostAPIV1BBucketNameForbidden) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameForbidden", 403)
}

func (o *PostAPIV1BBucketNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameConflict creates a PostAPIV1BBucketNameConflict with default headers values
func NewPostAPIV1BBucketNameConflict() *PostAPIV1BBucketNameConflict {
	return &PostAPIV1BBucketNameConflict{}
}

/*
PostAPIV1BBucketNameConflict describes a response with status code 409, with default header values.

A bucket with the same name already exists
*/
type PostAPIV1BBucketNameConflict struct {
}

// IsSuccess returns true when this post Api v1 b bucket name conflict response has a 2xx status code
func (o *PostAPIV1BBucketNameConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name conflict response has a 3xx status code
func (o *PostAPIV1BBucketNameConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name conflict response has a 4xx status code
func (o *PostAPIV1BBucketNameConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name conflict response has a 5xx status code
func (o *PostAPIV1BBucketNameConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name conflict response a status code equal to that given
func (o *PostAPIV1BBucketNameConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 b bucket name conflict response
func (o *PostAPIV1BBucketNameConflict) Code() int {
	return 409
}

func (o *PostAPIV1BBucketNameConflict) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameConflict", 409)
}

func (o *PostAPIV1BBucketNameConflict) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameConflict", 409)
}

func (o *PostAPIV1BBucketNameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1BBucketNameUnprocessableEntity creates a PostAPIV1BBucketNameUnprocessableEntity with default headers values
func NewPostAPIV1BBucketNameUnprocessableEntity() *PostAPIV1BBucketNameUnprocessableEntity {
	return &PostAPIV1BBucketNameUnprocessableEntity{}
}

/*
PostAPIV1BBucketNameUnprocessableEntity describes a response with status code 422, with default header values.

JSON request is invalid
*/
type PostAPIV1BBucketNameUnprocessableEntity struct {
}

// IsSuccess returns true when this post Api v1 b bucket name unprocessable entity response has a 2xx status code
func (o *PostAPIV1BBucketNameUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 b bucket name unprocessable entity response has a 3xx status code
func (o *PostAPIV1BBucketNameUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 b bucket name unprocessable entity response has a 4xx status code
func (o *PostAPIV1BBucketNameUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 b bucket name unprocessable entity response has a 5xx status code
func (o *PostAPIV1BBucketNameUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 b bucket name unprocessable entity response a status code equal to that given
func (o *PostAPIV1BBucketNameUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the post Api v1 b bucket name unprocessable entity response
func (o *PostAPIV1BBucketNameUnprocessableEntity) Code() int {
	return 422
}

func (o *PostAPIV1BBucketNameUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameUnprocessableEntity", 422)
}

func (o *PostAPIV1BBucketNameUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v1/b/{bucket_name}][%d] postApiV1BBucketNameUnprocessableEntity", 422)
}

func (o *PostAPIV1BBucketNameUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
PostAPIV1BBucketNameBody post API v1 b bucket name body
swagger:model PostAPIV1BBucketNameBody
*/
type PostAPIV1BBucketNameBody struct {

	// Maximum number of records in a block
	MaxBlockRecords int64 `json:"max_block_records,omitempty"`

	// Maximum size of a data block in bytes (default: 64MB)
	MaxBlockSize int64 `json:"max_block_size,omitempty"`

	// Size of quota in bytes
	QuotaSize int64 `json:"quota_size,omitempty"`

	// Type of quota. Can be 'NONE', 'FIFO', or 'HARD'
	QuotaType string `json:"quota_type,omitempty"`
}

// Validate validates this post API v1 b bucket name body
func (o *PostAPIV1BBucketNameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post API v1 b bucket name body based on context it is used
func (o *PostAPIV1BBucketNameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAPIV1BBucketNameBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAPIV1BBucketNameBody) UnmarshalBinary(b []byte) error {
	var res PostAPIV1BBucketNameBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
