// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIV1BBucketNameParams creates a new PutAPIV1BBucketNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV1BBucketNameParams() *PutAPIV1BBucketNameParams {
	return &PutAPIV1BBucketNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV1BBucketNameParamsWithTimeout creates a new PutAPIV1BBucketNameParams object
// with the ability to set a timeout on a request.
func NewPutAPIV1BBucketNameParamsWithTimeout(timeout time.Duration) *PutAPIV1BBucketNameParams {
	return &PutAPIV1BBucketNameParams{
		timeout: timeout,
	}
}

// NewPutAPIV1BBucketNameParamsWithContext creates a new PutAPIV1BBucketNameParams object
// with the ability to set a context for a request.
func NewPutAPIV1BBucketNameParamsWithContext(ctx context.Context) *PutAPIV1BBucketNameParams {
	return &PutAPIV1BBucketNameParams{
		Context: ctx,
	}
}

// NewPutAPIV1BBucketNameParamsWithHTTPClient creates a new PutAPIV1BBucketNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV1BBucketNameParamsWithHTTPClient(client *http.Client) *PutAPIV1BBucketNameParams {
	return &PutAPIV1BBucketNameParams{
		HTTPClient: client,
	}
}

/*
PutAPIV1BBucketNameParams contains all the parameters to send to the API endpoint

	for the put API v1 b bucket name operation.

	Typically these are written to a http.Request.
*/
type PutAPIV1BBucketNameParams struct {

	/* Body.

	   Parameters for updating a bucket
	*/
	Body PutAPIV1BBucketNameBody

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1BBucketNameParams) WithDefaults() *PutAPIV1BBucketNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v1 b bucket name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1BBucketNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) WithTimeout(timeout time.Duration) *PutAPIV1BBucketNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) WithContext(ctx context.Context) *PutAPIV1BBucketNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) WithHTTPClient(client *http.Client) *PutAPIV1BBucketNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) WithBody(body PutAPIV1BBucketNameBody) *PutAPIV1BBucketNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) SetBody(body PutAPIV1BBucketNameBody) {
	o.Body = body
}

// WithBucketName adds the bucketName to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) WithBucketName(bucketName string) *PutAPIV1BBucketNameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the put API v1 b bucket name params
func (o *PutAPIV1BBucketNameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV1BBucketNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
