// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIV1BBucketNameRenameParams creates a new PutAPIV1BBucketNameRenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV1BBucketNameRenameParams() *PutAPIV1BBucketNameRenameParams {
	return &PutAPIV1BBucketNameRenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV1BBucketNameRenameParamsWithTimeout creates a new PutAPIV1BBucketNameRenameParams object
// with the ability to set a timeout on a request.
func NewPutAPIV1BBucketNameRenameParamsWithTimeout(timeout time.Duration) *PutAPIV1BBucketNameRenameParams {
	return &PutAPIV1BBucketNameRenameParams{
		timeout: timeout,
	}
}

// NewPutAPIV1BBucketNameRenameParamsWithContext creates a new PutAPIV1BBucketNameRenameParams object
// with the ability to set a context for a request.
func NewPutAPIV1BBucketNameRenameParamsWithContext(ctx context.Context) *PutAPIV1BBucketNameRenameParams {
	return &PutAPIV1BBucketNameRenameParams{
		Context: ctx,
	}
}

// NewPutAPIV1BBucketNameRenameParamsWithHTTPClient creates a new PutAPIV1BBucketNameRenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV1BBucketNameRenameParamsWithHTTPClient(client *http.Client) *PutAPIV1BBucketNameRenameParams {
	return &PutAPIV1BBucketNameRenameParams{
		HTTPClient: client,
	}
}

/*
PutAPIV1BBucketNameRenameParams contains all the parameters to send to the API endpoint

	for the put API v1 b bucket name rename operation.

	Typically these are written to a http.Request.
*/
type PutAPIV1BBucketNameRenameParams struct {

	/* Body.

	   New name for the bucket
	*/
	Body PutAPIV1BBucketNameRenameBody

	/* BucketName.

	   Name of bucket
	*/
	BucketName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v1 b bucket name rename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1BBucketNameRenameParams) WithDefaults() *PutAPIV1BBucketNameRenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v1 b bucket name rename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1BBucketNameRenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) WithTimeout(timeout time.Duration) *PutAPIV1BBucketNameRenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) WithContext(ctx context.Context) *PutAPIV1BBucketNameRenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) WithHTTPClient(client *http.Client) *PutAPIV1BBucketNameRenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) WithBody(body PutAPIV1BBucketNameRenameBody) *PutAPIV1BBucketNameRenameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) SetBody(body PutAPIV1BBucketNameRenameBody) {
	o.Body = body
}

// WithBucketName adds the bucketName to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) WithBucketName(bucketName string) *PutAPIV1BBucketNameRenameParams {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the put API v1 b bucket name rename params
func (o *PutAPIV1BBucketNameRenameParams) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV1BBucketNameRenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param bucket_name
	if err := r.SetPathParam("bucket_name", o.BucketName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
